Update game_menu_impl.h
ParadoxZero/GameMenu-cpp pull request #14
Opened 2024-01-06 07:45 UTC by manichandra3

Improve menu initialization and error handling

- Refactored font loading to a separate function
- Handled font loading failures with exception
- Moved duplicate item processing outside the try block
- Updated variable naming for consistency
- Cleaned up unnecessary console outputs

2024-02-20 18:36 UTC, ParadoxZero commented
~You forgot to add the cpp file and its changes.~
Nvm, saw the inline methods.

2024-02-20 18:48 UTC, ParadoxZero commented
It's not clear from the PR, which duplication did you remove? The process items logic only existed in the constructor from what I can see.

Also check if you have any unpublished commits, since the `couts` are still there.

2024-02-20 18:48 UTC, ParadoxZero commented
Can you explain why you think we should load the fonts in GameMenu and not in the host?

2024-02-21 18:47 UTC, ParadoxZero requested changes

2024-02-21 18:47 UTC, ParadoxZero commented on src/game_menu_impl.h
> +            if (!_style.ItemFont->loadFromFile("path/to/your/font.ttf")) {
This is fundamentally wrong. Game menu class should receive the fonts already loaded by the host. 

Even if we need to add the API to load it from the `GameMenu` class, we can't hardcode a path like this.

2024-02-21 18:47 UTC, ParadoxZero commented on src/game_menu_impl.h
> +                throw std::runtime_error("Failed to load font");
I don't like `Exceptions` period. They are unpredictable and hard to debug. Throwing exception explicitly in constructor is bad design in my book.

While it's not relevant (as I don't think we should be loading font in the class), if at all we have failable initialization. We should create some static factory method to create the object instead.

2024-02-21 18:47 UTC, ParadoxZero commented on src/game_menu_impl.h
> +                std::cout << " Processing item " << menu_item.name << std::endl;
Remove these `couts` if possible. They are remains from a debugging session.

2024-02-22 07:29 UTC, manichandra3 commented
Sorry for the lazy PR, I am still new to development in C++ and I thought loading the fonts in the GameMenu will help with separation of concerns but I just realised that it is the complete opposite. Thank you for taking the time to guide me.

2024-02-22 07:29 UTC, closed without merging

2024-02-22 15:52 UTC, ParadoxZero commented
@manichandra3 no worries, we all are always learning. Feel free to fix this PR and reopening it. Reviewing it, I realized some potential issues in the lib. I have added them to list. You can take a stab at them too if you want, I review them for you :)